apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: a45da2c2q-nodejs 
  janus-idp.io/tekton: a45da2c2q-nodejs
  backstage.io/kubernetes-id: a45da2c2q-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: a45da2c2q-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml